DROP DATABASE isobar_ch;
DROP DATABASE isobar_ko;
DROP DATABASE isobar_my;
DROP DATABASE isobar_tw;
DROP DATABASE isobar_ru;

CREATE DATABASE IF NOT EXISTS isobar_ch CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS isobar_ko CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS isobar_my CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS isobar_tw CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS isobar_ru CHARACTER SET utf8;