CREATE DATABASE IF NOT EXISTS isobar_au;
CREATE DATABASE IF NOT EXISTS isobar_br;
CREATE DATABASE IF NOT EXISTS isobar_br2;
CREATE DATABASE IF NOT EXISTS isobar_ca;
CREATE DATABASE IF NOT EXISTS isobar_ch CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS isobar_de;
CREATE DATABASE IF NOT EXISTS isobar_dk;
CREATE DATABASE IF NOT EXISTS isobar_du;
CREATE DATABASE IF NOT EXISTS isobar_fr;
CREATE DATABASE IF NOT EXISTS isobar_hk;
CREATE DATABASE IF NOT EXISTS isobar_ind;
CREATE DATABASE IF NOT EXISTS isobar_it;
CREATE DATABASE IF NOT EXISTS isobar_jp;
CREATE DATABASE IF NOT EXISTS isobar_ko CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS isobar_ma;
CREATE DATABASE IF NOT EXISTS isobar_my CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS isobar_no;
CREATE DATABASE IF NOT EXISTS isobar_pt;
CREATE DATABASE IF NOT EXISTS isobar_se;
CREATE DATABASE IF NOT EXISTS isobar_th;
CREATE DATABASE IF NOT EXISTS isobar_tw CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS isobar_hu CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS isobar_ru CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS isobar_nl CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS isobar_sg CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS isobar_us2 CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS isobar_contacts CHARACTER SET utf8;


use mysql;
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_au',PASSWORD('5q0cZijGd'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_br',PASSWORD('qql21bcNI'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_br2',PASSWORD('FO86cVd50'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_ca',PASSWORD('zAVFxfGRy'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_ch',PASSWORD('O4BL03ryQ'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_de',PASSWORD('pMVH0sbbF'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_dk',PASSWORD('GsUnYYS5g'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_du',PASSWORD('XzN44HIFj'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_fr',PASSWORD('Q2VtCrueB'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_hk',PASSWORD('S6IRCGqjP'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_ind',PASSWORD('AUB2Nnjq0'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_it',PASSWORD('RgrMnLhPb'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_jp',PASSWORD('F7NBC4pHf'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_ko',PASSWORD('teTcsvwpj'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_ma',PASSWORD('xbt3ITUtt'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_my',PASSWORD('coBnAPczA'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_no',PASSWORD('sPLe1RqKg'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_pt',PASSWORD('8iYWRbRwu'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_se',PASSWORD('el08llubq'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_th',PASSWORD('woqTuvqQf'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_tw',PASSWORD('YtFVlfmuW'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_hu',PASSWORD('P21R37kDP'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_ru',PASSWORD('xEyH0y4sc'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_nl',PASSWORD('BrC77rTzf'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_sg',PASSWORD('KRDZ6VHOp'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_us2',PASSWORD('BZ7DqmV5A'));
INSERT INTO user (Host,User,Password) VALUES('localhost','isobar_contacts',PASSWORD('eH78chst7'));

flush privileges; 
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_au.* to isobar_au@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_br.* to isobar_br@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_br2.* to isobar_br2@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_ca.* to isobar_ca@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_ch.* to isobar_ch@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_de.* to isobar_de@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_dk.* to isobar_dk@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_du.* to isobar_du@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_fr.* to isobar_fr@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_hk.* to isobar_hk@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_ind.* to isobar_ind@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_it.* to isobar_it@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_jp.* to isobar_jp@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_ko.* to isobar_ko@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_ma.* to isobar_ma@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_my.* to isobar_my@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_no.* to isobar_no@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_pt.* to isobar_pt@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_se.* to isobar_se@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_th.* to isobar_th@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_tw.* to isobar_tw@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_hu.* to isobar_hu@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_ru.* to isobar_ru@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_nl.* to isobar_nl@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_sg.* to isobar_sg@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_us2.* to isobar_us2@localhost;
grant SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER on isobar_contacts.* to isobar_contacts@localhost;


flush privileges;
